% Created by Maxime Volery & Eduardo José González Coll 
% Date: 06.06.2022
function enabled = get_state()
tg = slrt('Baseline');
enabled = [ ...
    tg.getparam('enable1', 'Value'), ...
    tg.getparam('enable2', 'Value'), ...
    tg.getparam('enable3', 'Value'), ...
    tg.getparam('enable4', 'Value')];
end
