% Created by Maxime Volery & Eduardo José González Coll 
% Date: 06.06.2022
function write_pulse(f_, x_, x_unit, filename, title)
    % WRITE_PULSE saves some frequency data to a pulse text file that can
    % be loaded either by PULSE software and WRITE_PULSE function.
    % * f:          Frequency vector of the read data
    % * x:          Read data (same size as f), can be complex or real
    %               depending on the nature of the loaded data.
    % * x_unit:     Unit of the x amplitude signal
    % * filename:   Pulse .txt file name
    % * title:      Title to give to the curve (optional)
    
    if ~exist('title', 'var')
        title = '';
    end
    
    assert(numel(x_) == numel(f_));
    
    df = (f_(end) - f_(1))/(numel(f_) - 1);
    if isreal(x_)
        data_type = 'Real';
    else
        data_type = 'Complex';
    end
    
    dataStr = sprintf([...
        'Header Size:\t22\n' ...
        'Pulse Version:\t80\n' ...
        'Running Pulse Version:\tPULSE LabShop Fast Track Version 18.1.1.9 - 2014-01-16\n' ...
        'Decimal Symbol:\t.\n' ...
        'Date Format:\tdd/MM/yyyy\n' ...
        'Time Format:\tHH:mm:ss:mmm\n' ...
        'Data Type:\t%s\n' ...
        'Z-Axis type:\tLinear\n' ...
        'Z-Axis size:\t1\n' ...
        'Z-Axis unit:\n' ...
        'Z-Axis first value:\t0.0000000000e+000\n' ...
        'Z-Axis delta:\t1.0000000000e+000\n' ...
        'X-Axis type:\tLinear\n' ...
        'X-Axis size:\t%d\n' ...
        'X-Axis unit:\tHz\n' ...
        'X-Axis first value:\t%.10e\n' ...
        'X-Axis delta:\t%.10e\n' ...
        'AmplitudeUnit:\t%s\n' ...
        'Title:\t%s\n' ...
        'Power:\tFalse\n' ...
        'Ratio:\tTrue\n' ...
        '\n' ...
        'Z-index:\n' ...
        'Date:\t%s\n' ...
        'Time:\t%s:000\n' ...
        'Relative time:\t0.00000e+000\n' ...
        'Z-axis:\t0.0000000000e+000\n'], ...
        data_type, numel(x_), f_(1), df, x_unit, title, ...
        datestr(now(), 'dd/mm/yyyy'), ...
        datestr(now(), 'HH:MM:SS') ...
        );
    
    for i = 1:numel(f_)
        if isreal(x_)
            tmp = sprintf('%d\t%.10e\t%.10e\n', ...
                i, f_(i), x_(i));
        else
            tmp = sprintf('%d\t%.10e\t%.10e\t%.10e\n', ...
                i, f_(i), real(x_(i)), imag(x_(i)));
        end
        dataStr = [dataStr, tmp];
    end
    
    fid = fopen(filename, 'wt');
    fprintf(fid, dataStr);
    fclose(fid);
end
